# Generated by Django 4.0 on 2022-06-27 19:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_started', models.IntegerField(choices=[(1, 'STARTED'), (0, 'NOT STARTED')])),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=4, unique=True)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('number', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('name', models.CharField(max_length=200)),
                ('club_name', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('runners_A', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Runner_A', to='teams.runner')),
                ('runners_B', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Runner_B', to='teams.runner')),
                ('runners_C', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Runner_C', to='teams.runner')),
                ('runners_D', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Runner_D', to='teams.runner')),
                ('runners_E', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Runner_E', to='teams.runner')),
                ('runners_F', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Runner_F', to='teams.runner')),
            ],
            options={
                'ordering': ('number', 'name'),
            },
        ),
    ]
