# Generated by Django 4.0 on 2022-07-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='elapsed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='elapsed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
