# Generated by Django 4.0 on 2022-07-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_runner_elapsed_time_teams_elapsed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='elapsed_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='elapsed_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
